export const ADD_PIZZA_TO_CART = 'ADD_PIZZA_TO_CART';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';